= Neo4j Performance Tuning
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 1
:section: Neo4j in Production

.Goals
[abstract]
This guide explains Configuration and Performance Tuning best practices and troubleshooting tips. 

.Prerequisites
[abstract]
This guide describes how to configure and tune a Neo4j installation.
This includes topics such as cache sizing, JVM configuration, Memory Mapped IO (MMIO) settings and logical log configuration. 

[role=expertise]
{level}

toc::[]

== Configuration Best Practices

=== Hardware

* Provide as much memory as you can afford
* Use SSDs or other fast I/O if possible

=== Cache Sizing

The node_cache_size and relationship_cache_size should not be more than 1/3 of the total heap size. 
The JVM typically uses 1/3 of the heap for the "new generation", leaving 2/3 for the old generation. 
This is where the caches will live, along with any other longer term memory use. 
This space also needs additional headroom to all the garbage collector to operate correctly. 
Note that we also often suggest changing that initial ratio so that the "new generation" uses 1/2 the heap, rather than only 1/3, as Neo4j (and especially Cypher) often has high requirements for temporary memory use, especially when many concurrent threads are accessing it. 
However, that reduces the size available for the caches accordingly.

=== Specifying JVM tuning properties

Tuning the standalone server is achieved by editing the `neo4j-wrapper.conf` file in the conf directory of NEO4J_HOME.

The heap space parameter is the most important one for Neo4j, since this governs how many objects you can allocate.
When it comes to heap space the general rule is: the larger heap space you have the better, but make sure the heap fits in the RAM memory of the computer.
If the heap is paged out to disk performance will degrade rapidly.
Having a heap that is much larger than what your application needs is not good either, since this means that the JVM will accumulate a lot of dead objects before the garbage collector is executed, this leads to long garbage collection pauses and undesired performance behavior.

Typically we aim to have those memory_mappings cover the entire size of the on-disk store, to ensure all the graph content is cached into memory.
The remaining memory can then be split between the Neo4j heap and the rest of the operating system (& other processes).

Edit your neo4j-wrapper file to set the heap size. It is recommended that the initmemory and the maxmemory properties be set to the same number.

For example:

----
wrapper.java.initmemory=24512
wrapper.java.maxmemory=24512
----

Finally make sure that the OS has some memory left to manage proper file system caches. 
This means, if your server has 8GB of RAM don't use all of that RAM for heap (unless you have turned off memory mapped buffers), but leave a good part of it to the OS.


=== Memory Mapped IO Settings

You should adopt the MMIO cache settings to fit your graph size in `neo4j.properties` and not rely on the default values.
To determine the graph size:

----
run 'ls -alh /neo4j/data/graph.db/neostore*'

-rw-r--r-- 1 neo4j neo4j 149M Nov 11 16:39 neostore.nodestore.db
-rw-r--r-- 1 neo4j neo4j 2.2G Nov 11 16:39 neostore.propertystore.db
-rw-r--r-- 1 neo4j neo4j 128 Nov 11 16:14 neostore.propertystore.db.arrays
-rw-r--r-- 1 neo4j neo4j 3.0G Nov 11 16:39 neostore.propertystore.db.strings
-rw-r--r-- 1 neo4j neo4j 687M Nov 11 16:39 neostore.relationshipstore.db
----

Set the MMIO settings are at or just a little bigger (30% or so) than they are:

----
neostore.nodestore.db.mapped_memory=200M
neostore.propertystore.db.mapped_memory=2300M
neostore.propertystore.db.arrays.mapped_memory=5M
neostore.propertystore.db.strings.mapped_memory=3200M
neostore.relationshipstore.db.mapped_memory=800M
----

=== Server Configuration

The main configuration file for the server can be found at `conf/neo4j-server.properties`. 

=== Logical Logs

Logical logs in Neo4j are the journal of which operations happens and are the source of truth in scenarios where the database needs to be recovered after a crash or similar. 
Logs are rotated every now and then (defaults to when they surpass 25 Mb in size) and the amount of legacy logs to keep can be configured. 

It is recommended that the `keep_logical_logs` parameter be set to `7 days`

=== Setting the Number of Open Files on Linux

The usual default of `1024` is often not enough, especially when many indexes are used or a server installation sees too many connections (network sockets count against that limit as well). 
Users are therefore encouraged to increase that limit to a healthy value of `40000` or more, depending on usage patterns. 
Setting this value via the ulimit command is possible only for the root user and that for that session only.
To set the value system wide you have to follow the instructions for your platform (http://docs.neo4j.org/chunked/stable/linux-performance-guide.html#_setting_the_number_of_open_files[Linux]).

[role=side-nav]
=== Recommended

* http://docs.neo4j.org/chunked/stable/operations.html[Operations,role=manual]
* http://docs.neo4j.org/chunked/stable/configuration.html[Configuration & Performance,role=manual]
* http://maxdemarzi.com/2013/11/25/scaling-up/[Scaling Up Neo4j,role=blog]
* link:/support[Neo4j Professional Support]

=== Troubleshooting

=== GC pressure, frequent garbage collections

* Heap is too small, or caches are too big. See recommended setup

\\TODO this seems unfinished ^

[role=side-nav]
=== Further Reading

* link:/books[The Neo4j Bookshelf]
* http://watch.neo4j.org[The Neo4j Video Library]
* http://gist.neo4j.org/[GraphGists]
