
[#driver-configuration]
=== Driver Configuration

From Neo4j version **4.0** and onwards, the default encryption setting is *off* by default and Neo4j will no longer generate self-signed certificates.
This applies to default installations, installations through Neo4j Desktop and Docker images.
You can https://neo4j.com/docs/migration-guide/4.0/upgrade-driver/#_configure_ssl_policy_for_bolt_server_and_https_server[verify the encryption level of your server^] by checking the `dbms.connector.bolt.enabled` key in `neo4j.conf`.

.Table Scheme Usage
|===
| Certificate Type | Neo4j Causal Cluster | Neo4j Standalone Server  | Direct Connection to Cluster Member

| *Unencrypted*
| `neo4j`
| `neo4j`
| `bolt`

| *Encrypted with Full Certificate*
| `neo4j+s`
| `neo4j+s`
| `bolt+s`


| *Encrypted with Self-Signed Certificate*
| `neo4j+scc`
| `neo4j+scc`
| `bolt+scc`

| *https://neo4j.com/aura/[Neo4j Aura^]*
| `neo4j+s`
| N/A
| N/A

|===

There is https://neo4j.com/docs/driver-manual/current/client-applications/#driver-connection-uris[more information on Driver connection URI's in the Drivers Manual^].

Please review your https://neo4j.com/docs/operations-manual/4.0/security/ssl-framework/[SSL Framework settings^] when going into production.
If necessary, you can also https://medium.com/neo4j/getting-certificates-for-neo4j-with-letsencrypt-a8d05c415bbd[generate certificates for Neo4j with Letsencrypt^]

