= Neo4j Graph Data Science
:section: Graph Data Science
:section-link: graph-data-science
:section-level: 1
:slug: graph-data-science
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1
:author: Jennifer Reif
:category: documentation
:tags: graph-data-science, nlp, graph-algorithms

[#neo4j-graph-data-science]
There are a variety of ways to interact with and use graph data in Neo4j.
This guide introduces the different products we provide at Neo4j to suit your diverse business and technology needs and show you how to get started using them.

From our core product (the graph database) to visualization for business users, we provide a variety of opportunities to maximize your business and simplify your data.

[#graph-data-science-library]
== Graph Data Science Library

Neo4j Graph Data Science is a library that provides efficiently implemented, parallel versions of common graph algorithms for Neo4j 3.x and Neo4j 4.x exposed as Cypher procedures.

link:/developer/graph-algorithms[Graph Algorithms, role="medium button"]

[#graph-data-science-playground]
== NEuler: The Graph Data Science Playground

NEuler (Neo4j Euler) is a link:/developer/graph-apps/[graph app^] that helps Neo4j Desktop users get started with the Neo4j Graph Data Science Library.

* https://medium.com/neo4j/introducing-neuler-the-graph-algorithms-playground-d81042cfcd56[Introducing NEuler — The Graph Algorithms Playground^]  +
* https://medium.com/neo4j/the-graph-algorithms-playground-and-graph-data-science-library-69575a0fb329[The Graph Algorithms Playground and Graph Data Science Library^]

[#nlp]
== Neo4j NLP

Neo4j offers powerful querying capabilities for structured data, but a lot of the world's data exists in text documents.
NLP techniques can help to extract the latent structure in these documents.

link:/developer/nlp[Neo4j NLP, role="medium button"]

[#graph-data-science-training]
== Graph Data Science Training

GraphAcademy has self-paced online training classes to help you get up to speed with Graph Data Science.

* https://neo4j.com/graphacademy/online-training/data-science/[Data Science with Neo4j^]  +
* https://neo4j.com/graphacademy/online-training/applied-graph-algorithms/[Applied Graph Algorithms with Neo4j 3.5^]

Both of these training courses can be completed in half a day.
