= Neo4j Graph Data Science
:section: Graph Data Science
:section-link: graph-data-science
:section-level: 1
:slug: graph-data-science
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1
:author: Jennifer Reif
:category: documentation
:tags: graph-data-science, nlp, graph-algorithms

[#neo4j-graph-data-science]
Although Neo4j has traditionally been used for transaction workloads, in recent years it is increasingly being used at the heart of graph analytics platforms.
This guide introduces the tools available for applying graph analytics to your connected data.

[#graph-data-science-library]
== Graph Data Science Library

Neo4j Graph Data Science is a library that provides efficiently implemented, parallel versions of common graph algorithms for Neo4j 3.x and Neo4j 4.x exposed as Cypher procedures.

link:/developer/graph-algorithms[Graph Algorithms, role="medium button"]

[#graph-data-science-playground]
== NEuler: The Graph Data Science Playground

NEuler (Neo4j Euler) is a link:/developer/graph-apps/[graph app^] that helps Neo4j Desktop users get started with the Neo4j Graph Data Science Library.

* https://medium.com/neo4j/introducing-neuler-the-graph-algorithms-playground-d81042cfcd56[Introducing NEuler — The Graph Algorithms Playground^]
* https://medium.com/neo4j/the-graph-algorithms-playground-and-graph-data-science-library-69575a0fb329[The Graph Algorithms Playground and Graph Data Science Library^]

[#nlp]
== Neo4j NLP

Neo4j offers powerful querying capabilities for structured data, but a lot of the world's data exists in text documents.
NLP techniques can help to extract the latent structure in these documents.

link:/developer/nlp[Learn more about NLP, role="medium button"]

[#graph-data-science-training]
== Graph Data Science Training

GraphAcademy has self-paced online training classes to help you get up to speed with Graph Data Science.

* https://neo4j.com/graphacademy/online-training/data-science/[Data Science with Neo4j^]  +
* https://neo4j.com/graphacademy/online-training/applied-graph-algorithms/[Applied Graph Algorithms with Neo4j 3.5^]

Both of these training courses can be completed in half a day.
