= Hosting Neo4j on EC2 on AWS
:slug: neo4j-cloud-aws-ec2-ami
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 1
:section: Neo4j in the Cloud
:section-link: guide-cloud-deployment

.Goals
[abstract]
This guide explains how to deploy Neo4j on Amazon's EC2 platform.

.Prerequisites
[abstract]
You should know how to run and operate Neo4j locally.
Knowledge of link:/developer/language-guides[remote drivers] to access Neo4j from your application helps you connect to your cloud-hosted database.

toc::[]

Before continuing with the guide make sure you've http://docs.aws.amazon.com/cli/latest/userguide/installing.html[installed the AWS Command Line Interface^].
If you're not comfortable using the command line you can https://aws.amazon.com/marketplace/pp/B071P26C9D[install Neo4j using the AWS web console^].

Let's get started!

== Create EC2 key pair

First, we need to create an http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[EC2 key pair^] that we will use to connect to our instance via SSH.

```
export KEY_NAME="Neo4j-AWSMarketplace-Key"
aws ec2 create-key-pair \
  --key-name $KEY_NAME \
  --query 'KeyMaterial' \
  --output text > $KEY_NAME.pem
```

If you have an existing key that you'd like to use instead, you can set `KEY_NAME` to the name of that key pair and ignore the 2nd command.


== Create security group

Now we'll create a http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html[security group^], which will allow us to control access to our instance.
Run the following command to create a new security group:

[source,text]
----
export GROUP="neo4j-sg"
aws ec2 create-security-group \
  --group-name $GROUP \
  --description "Neo4j security group"
----

Next let's open Neo4j's HTTP, HTTPS, and Bolt ports so we can access the server from our application.
We will also open the SSH port so we can remotely access the instance.

[source,text]
----
for port in 22 7474 7473 7687; do
  aws ec2 authorize-security-group-ingress --group-name $GROUP --protocol tcp --port $port --cidr 0.0.0.0/0
done
----

If you have an existing group that you'd like to use instead, set `GROUP` to the name of that group and ignore the rest of the commands.


[[start-up-instance]]
== Start up the instance

We are now ready to start up a Neo4j instance.
We will use the `image-id` for us-east-1, but there are link:#other-regions[corresponding image ids for other regions].

[source,text]
----
aws ec2 run-instances \
  --image-id ami-2a652655 \
  --count 1 \
  --instance-type m3.medium \
  --key-name $KEY_NAME \
  --security-groups $GROUP \
  --query "Instances[*].InstanceId" \
  --region us-east-1
----

We don't yet have a Public DNS Name but it should be available in a few seconds.

We can run the following command to find out what it is:

[source,text]
----
aws ec2 describe-instances \
  --instance-ids [InstanceId] \
  --query "Reservations[*].Instances[*].PublicDnsName" \
  --region us-east-1
----

Please note that your security group settings may affect whether or not a public DNS name is
associated with your instance.  If this command does not work for you, check to make sure your
security group is properly configured, and is not associated with a VPC.

Now let's navigate to `https://[PublicDnsName]:7473` and login with the user name `neo4j` and password `neo4j`.

Note that in some methods of launching neo4j on AWS, such as via the AWS marketplace, the password of
an instance will be automatically set to the instance ID you launched.  In other cases, such as when
launching enteprise AMIs directly, the password is left as the default "neo4j".  In either case, we
recommend changing the password immediately after you launch.


== How do I SSH into the instance?

You can run the following command to SSH into the instance:

[source,text]
----
ssh -i $KEY_NAME.pem ubuntu@[PublicDnsName]
----

You might get an error about the permissions on the pem file so don't forget to make sure it isn't accessible by any other users.

[source,text]
----
chmod 600 $KEY_NAME.pem
----


== How the AWS Virtual Machine Works

Please consult link:/developer/guide-cloud-deployment/neo4j-cloud-vms[Neo4j Cloud VMs] for details on internals of AWS VMs, including how to stop and start system services, configure Neo4j inside of the VM, and more.


[[other-regions]]
== How do I find the `image-id` for other regions?

If we're in a different region than us-east-1, we can run the following command to find out the `image-id` for that region.

[source,text]
----
aws ec2 describe-images \
  --filters "Name=name,Values=neo4j-enterprise-1-3.4.1*" \
  --region us-east-1 --query "Images[*].ImageId"
----

We can then substitute that `image-id` when link:#start-up-instance[starting up an instance].

This same filter command can be used to locate AMIs for neo4j-community.


== Terminating the instance

Once we've finished using the instance we can run the following command to terminate it:

```
aws ec2 terminate-instances \
  --instance-ids [InstanceId] \
  --region us-east-1
```

== Questions?

You can ask questions and connect with other people launching Neo4j in the cloud at the 
https://community.neo4j.com/c/neo4j-graph-platform/cloud[cloud topic on the Community Site].
