= Graph Applications
:slug: graph-apps
:level: Beginner
:section: Graph Apps
:section-link: graph-apps
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1

.Goals
[abstract]
This guide explains what a Graph Application is for Neo4j.

.Prerequisites
[abstract]
It helps if you have read the section on link:/developer/get-started/graph-database/[graph databases], as well as have downloaded and are familiar with link:/developer/neo4j-desktop/[Neo4j Desktop].

[#what-are-graphapps]
== What are Graph Apps?

A Graph app is a Single Page Application (SPA) built with HTML and JavaScript which interact with Neo4j databases through https://neo4j.com/desktop/[Neo4j Desktop^].
They can be developed by anyone - community members, partners, enterprises, and more - and are a convenient way of trying out ideas or building useful tools with Neo4j databases.
A developer could take an existing SPA and package it into a graph app or start from scratch with a new idea.

[#available-graphapps]
== What Graph Apps are Available?

A full list of published graph apps for Neo4j is provided on our https://install.graphapp.io/[Graph App Gallery^].
From visualization tools to database/query monitoring, there is a graph app for many different kinds of needs.

[#build-graphapp]
== How Can I Build my own Graph App?

We have a guide to step through the process of link:/developer/graph-app-development/[building your own graph app], so you can provide your own unique tool on top of Neo4j.
We cannot wait to see what you build!

[#graphapp-community]
== Graph App Topic on Neo4j Community

If you have any questions, comments, or would like to show off your own Graph App then there is a dedicated https://community.neo4j.com/c/neo4j-graph-platform/graph-apps/95[Graph Apps^] category on the https://community.neo4j.com/[Neo4j Community site^].