source 'https://rubygems.org'

gem 'sinatra'

#gem 'neo4j', '~>3.0.0'
#gem 'neo4j', git: 'git@github.com:neo4jrb/neo4j.git'
gem 'neo4j', path: '/Users/andreasronge/projects/neo4j'
group 'development' do
  gem 'pry'
  gem 'shotgun'
end
