== Neo4j Developer Resources

This is the repository with the source content for the http://neo4j.com _developer resources_ section.

The content is written as textual format in http://asciidoctor.org[AsciiDoc] rendered with asciidoctor using templates to HTML and pushed to the `gh-pages` branch or to wordpress.
Install asciidoctor ruby gems with `bundle install` in the main directory.

You can render a single document to its `index.html` by calling `render.sh path/to/doc.adoc` +
(e.g. `render.sh in-production/guide-cloud-deployment/guide-cloud-deployment.adoc`) or all pages at once with `render.sh`

=== Guides

Most of the documents in this developer resources section are organized as a guide. 
Those guides come with a consistent structure and similar use of language and assets. 
Each of the guides lives in its own directory and is rendered into an `index.html` file for publication.
You can run the rendering process by calling `render.sh` on the command line.

A guide has this general structure:

1. goal for this guide
2. prerequisite with links to relevant sections
3. recommended experience level (Beginner, Intermediate, Advanced)
4. Multiple sections and subsections outlining the content
use a welcoming and helpful, not overly complex or eloquent language with examples in code, pictures or videos
5. each top level (`===`) section can be followed by a sidebar section which will be rendered on the right side with links to follow up information (internal links, calls to action, external links)

Please see the link:./guide_template.adoc[example guide template file] for a blueprint of the document structure needed.
And as link:./guide_template.html[rendered document].

==== Calls to Action

* http://neo4j.com/events?type=Webinar[Webinar Registration]
* http://neo4j.com/books[Book Downloads]
* http://neo4j.com/newsletter/[Newsletter Registration]
* http://neo4j.com/online-training[Online Training]
* http://neo4j.com/events?type=Training[Offline Training Classes]
* http://neo4j.com/download[Neo4j Download]
* http://neo4j.com/?s=+whitepaper[Whitepapers]

==== Internal and External Content

* Other developer-resources and neo4j.com pages
* http://neo4j.com/docs/chunked/stable[Manual Pages] and Articles
* Blog Posts (http://neo4j.com/blog, http://blog.bruggen.com?view=mosaic[Rik], http://maxdemarzi.com[Max], http://www.markhneedham.com/blog/category/databases-2/neo4j/[Mark], http://www.kennybastani.com/[Kenny], http://jexp.de/blog[Michael], http://iansrobinson.com/[Ian], http://jimwebber.org/[Jim], ...)
* http://neo4j.com/events?type=Meetup[Local Meetup Groups]
* http://watch.neo4j.org[Webinar/Talk Recordings]

=== Example Applications per Language, Stack and Driver

To explain how to use Neo4j with different programming languages we provide an intro section per language, located in `language-guides/<language>/<language>.adoc`.

To show how the different drivers for that language would be used/integrated we also provide small example projects/setups in the `language-guides/<language>/<driver>` directories.

The example application is a simple, single-page movies app based on the Neo4j-Movies dataset that comes with the Neo4j-Server (`:play movies` in the Neo4j-Browser).

See an example running http://my-neo4j-movies-app.herokuapp.com/[here on Heroku].

The HTML page uses jQuery ajax requests to query 3 REST-Endpoints in the backend for `/search`, `/movie` and `/graph`

* `/search` lists the movies found by title
* `/movie` returns details for a single movie
* `/graph` renders the full graph as a basic d3-visualization

This is our current list of projects:

* java/jdbc
* java/server-extension
* python/py2neo (Thanks Nigel & Mark)
* python/neo4j-rest-client (Thanks Javier)
* clojure/neocons (Thanks Rohit)
* go/cq (Thanks Wes)
* perl/neo4p (Thanks Mark)
* php/neoclient (Thanks Christophe)
* php/neo4jphp (Thanks Josh)
* ruby/neo4jrb and ruby/neo4j-core (Thanks Andreas)
