== Neo4j Movies Example Application

=== Stack

* Neo4j-Server Extension
* Jersey JAX-RS Resource
* Neo4j-Execution-Engine with Cypher
* Neo4j-Server
* Frontend: jquery, bootstrap, http://d3js.org/[d3.js]

=== Endpoints:

Get Movie

----
// JSON object for single movie with cast
curl http://localhost:7474/movie/The%20Matrix

// list of JSON objects for movie search results
curl http://localhost:7474/movie/search?q=matrix

// JSON object for whole graph viz (nodes, links - arrays)
curl http://localhost:7474/movie/graph
----

=== Setup

Spark is a micro-webframework to easily define routes for endpoints and provide their implementation.
In our case the implementation calls the `MovieService` which has one method per endpoint that returns Java collections
which are turned into JSON using Gson.

The `MovieService` uses the Neo4j-JDBC driver to execute queries against the transactional endpoint of Neo4j-Server.
You add the dependency to the JDBC driver in your `pom.xml`:

[source,xml]
----
include::pom.xml[tags=jdbc-dependency]
----

To use the JDBC driver you provide a connection URL, e.g. `jdbc:neo4j:localhost:7474`, get a `Connection`
which then can be used to create `PreparedStatement`s with your Cypher query.

You would then set parameters on your statement, please note that only numeric parameter-names are possible, _starting from 1_.

To access the `ResultSet` you call the cursor method `rs.next()` in a while loop, within which you can access the result-data by `rs.getString("columnName")` where the column name is the `RETURN` clause alias for each column.

[source,java]
----
Connection con = DriverManager.getConnection("jdbc:neo4j://localhost:7474/");

String query = "MATCH (:Movie {title:{1}})<-[:ACTED_IN]-(a:Person) RETURN a.name as actor";

try (PreparedStatement stmt = con.prepareStatement(query)) {

    stmt.setString(1,"The Matrix");

    try (ResultSet rs = stmt.executeQuery()) {
        while(rs.next()) {
             System.out.println(rs.getString("actor"));
        }
    }
}
----

=== Run locally:

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser].
Then install the Movies data-set with `:play movies`, click the statement, and hit the triangular "Run" button.

Start this application with:

[source,shell]
----
mvn compile exec:java
----

Go to http://localhost:8080

You can search for movies by title or and click on any entry .

=== Deploy to Heroku

include::../../Readme.adoc[tags=heroku]
