= Contributing to Neo4j
:slug: contribute
:section: Contributing to Neo4j
:section-link: contribute
:section-level: 1
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1

[#neo4j-contribute]
Looking for a place to contribute to the Neo4j ecosystem?
This is a great place to start.
Here you will find guides from Neo4j’s community of contributors.


[#finding-help]
== Help Others in the Community

Want to help others?
There are a number of great resources the Neo4j community uses to get quick help from graph database experts.
Don't hesitate to ask when you’re stuck and looking for help.  Also, if you're familiar with a particular topic area, please jump in and lend a hand for your fellow graphistas.

The primary home for the Neo4j Community is our https://community.neo4j.com[Neo4j Online Community^] site and forum.

We also have some other places the community asks questions.

* http://stackoverflow.com/questions/tagged/neo4j[Neo4j on StackOverflow^]
* http://twitter.com/neo4j[Social: Neo4j on Twitter^]
* http://neo4j.com/slack[Chat: Neo4j-Users Slack^]
* http://www.quora.com/Neo4j[Neo4j on Quora^]
* http://github.com/neo4j/neo4j/issues[Raise Issues: GitHub Issues^]
* link:https://groups.google.com/group/neo4j[Neo4j Google Group^], link:https://groups.google.com/group/neo4jfr[(Français)^], link:https://groups.google.com/group/neo4jes[(Español)^], link:https://groups.google.com/group/neo4j-biotech[(biotech)^], link:https://groups.google.com/group/graph-software-analytics[(graph-software-analytics)^],


=== Want to Help Community Members Ask Questions in a Helpful Manner?

Ask them to please supply as much contextual information in your questions as possible.
This will help community members provide the best solution quickly and efficiently.

* Neo4j version, library/driver name and versions, operating system, Java version
* programming language and version
* explanation of issue
* code and configuration used
* graph-structure (ascii art or graphics)
* any other helpful information, including steps taken before problem occurred

If appropriate, they can also include the following:

* application output
* log-files (`data/log/\*.log` , `data/graph.db/messages.log`)
* exceptions with *full* stacktraces

[#speaking]
== Sharing your Love of Graphs

No matter where you live in the world, there are plenty of ways to share your love of graphs
and help others understand the importance of relationships.

With thousands of technology and business *conferences* occuring every year around the world, 
you can present to your peers and become a recognized expert in your field.  Neo4j, via the
https://neo4j.com/speaker-program/[*Neo4j Speaker Program*], can also help and reimburse
travel expenses for community members speaking at many of the top conferences.

There are also hundreds of face-to-face https://www.meetup.com/[*Neo4j meetup groups*] in communities
around the world.  Many of these meetup groups regularly look for speakers to share their stories.

The [*Neo4j Online Meetup*] is a way for you to meet the global community online and share your story.
We select talks from our https://community.neo4j.com/[Neo4j Community site]. To submit your talk, 
post in in the #projects (if including a link to github or website) or #content (if linking to a blog post,
slideshow, video, or article) categories.


[#contributing]
== Other Ways to Contribute

The Neo4j project is an open source effort to bring fast, complex data storage and processing to life.
Every form of help is highly appreciated by the community.
Note that you can contribute to Neo4j also by providing documentation or giving feedback on the current documentation.
Basically, in all the places where you can get help, there is also room for contributions.

* link:contributing-code[Contributing Code^]
* link:cla[Contributors License Agreement^]
* GitHub http://github.com/neo4j/neo4j/issues[Issues^] and http://github.com/neo4j/neo4j/pulls[Pull Requests^]
* See the https://github.com/neo4j/neo4j/graphs/contributors[list of contributors^]


[#develop-neo4j]
== Tools for Developing Neo4j

We are happy users of the following tools that we use daily to develop Neo4j.

* IDE: https://www.jetbrains.com/idea/[IntelliJ Idea by JetBrains^] - *Thank you so much for the https://www.jetbrains.com/idea/buy/choose_edition.jsp?license=OPEN_SOURCE[OSS license^]!* and Eclipse
* Build System: https://www.jetbrains.com/teamcity/[TeamCity by JetBrains^] - *Thank you so much for the https://www.jetbrains.com/teamcity/buy/choose_edition.jsp?license=OPEN_SOURCE[OSS license^]!*
* Profiler: Yourkit, VisualVM, jvmtop, Java Mission Control, Flight Recorder
* Version Control: Git & http://github.com/neo4j[GitHub^]
* Issue Management: Trello and http://github.com/neo4j/neo4j/issues[GitHub issues^]
* Team Communication: Neo4j Community Site, Slack, Google Hangouts, and Skype
* Pair Programming: Team Viewer, join.me
* Documents: Google Docs
* Manual, GraphGists, Presentations: http://asciidoctor.org[AsciiDoctor^]
* Programming Language: Java, Build-Tool - Maven
* Libraries - JVM: Scala, Parboiled, Google Collections, JMH, Jetty, Jersey, Jackson, Apache Commons, JUnit
* Libs & Tools: Javascript: D3.js, Angular.js, Grunt, Bower


[#integration-dev]
== Tools, Libraries, and Drivers

Neo4j is supported by a rich ecosystem of libraries, tools, drivers and guides provided by partners, users and community contributors.
We want to give an overview about what is available and link to the original sources.
We try to focus on the freely available solutions here and provide links to commercial options were appropriate.

Read more about it in our link:../integration/ecosystem[Integrations Section^].
