= What is the Neo4j GraphGist Project?
:level: Beginner
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 1
:section: Working with Data
:section_link:working-with-data
:graphgist: http://gist.neo4j.org

.Goals
[abstract]
This article introduces the GraphGist project and guides the reader through the process of creating a simple GraphGist.

.Prerequisites
[abstract]
You should have a good understanding of the Neo4j's link:/developer/get-started/graph-database#property-graph[property graph data model], and its query language, link:/developer/cypher[Cypher].

[role=expertise]
{level}

{graphgist}[Neo4j Graph Gists] are an easy way to create and share your documents containing not just prose, structure
and pictures but most importantly **example graph models and use-cases** expressed in Neo4j's query language, link:/developer/cypher[Cypher].

These documents are written in a simple, textual markup language (http://asciidoctor.org[AsciiDoc]) and rendered in your browser as rich and interactive web pages that you can quickly evolve from describing simple how-tos or questions to providing an extensive use-case specification.

To see the expressive power of this approach, here are some winners of our past community competitions:

== Examples

[none]
* **Finance** {graphgist}/?github-neo4j-contrib%2Fgists%2F%2Fother%2FBankFraudDetection.adoc[Bank Fraud Detection] by https://twitter.com/kennybastani[@kennybastani]
* **Sports** {graphgist}/?8019511[Alpine Skiing seasons] by https://twitter.com/pac_19[@pac_19]
* **Life Science** {graphgist}/?7968633[Pharmaceutical Drugs and their Targets] by https://twitter.com/joshkunken[@joshkunken]
* **Resources** {graphgist}/?8141937[Piping Water] by https://twitter.com/shaundaley1[@shaundaley1]
* **Retail** {graphgist}/?8139605[Single Malt Scotch Whisky] by https://twitter.com/patbaumgartner[@patbaumgartner]
* **Telecommunications** {graphgist}/?8526106[Amazon Web Services Global Infrastructure Graph] by https://twitter.com/aidanjcasey[@aidanjcasey]
* **Infrastructure** {graphgist}/?8635758[Roads, Nodes and Automobiles] by http://www.jacqui.tk[@tekiegirl]
* **Recommendation** {graphgist}/?8173017[Movie Recommendations with k-NN and Cosine Similarity] by http://twitter.com/_nicolemargaret[@_nicolemargaret]
* **Fun** {graphgist}/?6506717[Chess Games and Positions] by https://twitter.com/wefreema[@wefreema]
* **Many more** examples can be found in the https://github.com/neo4j-contrib/graphgist/wiki[GraphGist Collection]

== Getting Started

=== Follow these easy steps

. **Log into** your GitHub account
. **Choose** one of the examples listed above, and click the green **page source** button.
. **Fork** the original GraphGist into your own account and **start to edit** the prose, images, setup and use-case Cypher queries.
. **Paste** the Github Gist URL into the top right URL box of any {graphgist}[GraphGist] page; your Gist will be loaded and rendered immediately.
. **Reload** your GraphGist page whenever you update your document.
. **Share** your GraphGist with your colleagues, friends or us.
. **Submit** via "submit" link in the footer.

++++
<iframe src="//player.vimeo.com/video/74279113" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
++++

Below is an example of an http://gist.neo4j.org/?f528552b7a1f9cb4fa2a[Example-GraphGist] and how it is rendered (https://gist.github.com/jexp/f528552b7a1f9cb4fa2a[source]):

++++
<iframe src="http://gist.neo4j.org/?f528552b7a1f9cb4fa2a" width="800" height="800"></iframe>
++++
