= What is the Neo4j GraphGist Project?
:slug: graphgist
:level: Beginner
:section: Graph Data Modeling
:section-link: data-modeling
:graphgist: https://neo4j.com/graphgists/
:graphgists_list: https://neo4j.com/graphgists/
:graphgist_portal: http://portal.graphgist.org/
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1

.Goals
[abstract]
This article introduces the GraphGist project and guides the reader through the process of creating and submitting a simple GraphGist.

.Prerequisites
[abstract]
You should have a good understanding of the Neo4j's link:/developer/get-started/graph-database#property-graph[property graph data model]. It is also helpful to know a bit about the link:/developer/cypher[Cypher query language].

[role=expertise]
{level}

[#about-graphgists]
{graphgists_list}[Neo4j Graph Gists] are an easy way to create and share your documents containing not just prose, structure and pictures but most importantly **example graph models and use cases** expressed in Neo4j's query language, link:/developer/cypher[Cypher].
They are very helpful to share knowledge among the Neo4j community and help developers and others within your own organization by showing real-life solutions.

These documents are written in a simple, textual markup language (http://asciidoctor.org[AsciiDoc^]) and are rendered in your browser as rich and interactive web pages that you can quickly evolve by describing simple how-tos or questions to providing an extensive use case specification.

To see the expressive power of this approach, here are some winners of our past community competitions:

[#graphgist-examples]
== Examples

[none]
* **Finance** {graphgist}/?github-neo4j-contrib%2Fgists%2F%2Fother%2FBankFraudDetection.adoc[Bank Fraud Detection] by https://twitter.com/kennybastani[@kennybastani^]
* **Sports** {graphgist}/?8019511[Alpine Skiing seasons] by https://twitter.com/pac_19[@pac_19^]
* **Life Science** {graphgist}/?7968633[Pharmaceutical Drugs and their Targets] by https://twitter.com/joshkunken[@joshkunken^]
* **Resources** {graphgist}/?8141937[Piping Water] by https://twitter.com/shaundaley1[@shaundaley1^]
* **Retail** {graphgist}/?8139605[Single Malt Scotch Whisky] by https://twitter.com/patbaumgartner[@patbaumgartner^]
* **Telecommunications** {graphgist}/?8526106[Amazon Web Services Global Infrastructure Graph] by https://twitter.com/aidanjcasey[@aidanjcasey^]
* **Infrastructure** {graphgist}/?8635758[Roads, Nodes and Automobiles] by http://www.jacqui.tk[@tekiegirl^]
* **Recommendation** {graphgist}/?8173017[Movie Recommendations with k-NN and Cosine Similarity] by http://twitter.com/_nicolemargaret[@_nicolemargaret^]
* **Fun** {graphgist}/?6506717[Chess Games and Positions] by https://twitter.com/wefreema[@wefreema^]
* **Many more** examples can be found in the https://github.com/neo4j-contrib/graphgist/wiki[GraphGist Collection^]

[#graphgist-info]
== Getting Started

More information on getting started building your own GraphGist is available on the {graphgist_portal}[GraphGist Portal^].
