= Neo4j Aura Database-as-a-Service
:slug: aura-cloud-dbaas
:section: Neo4j Cloud DBaaS
:section-link: aura-cloud-dbaas
:section-level: 1
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1

[#neo4j-dbaas]
link:/aura[Neo4j Aura^] is a fully-managed cloud database developed by the same people that built Neo4j.

This guides and tutorials below will help you get started:

[#get-started-aura]
== Get Started with Neo4j Aura

Is it your first time using Neo4j Aura?
You've come to the right place!
The tutorial below will guide you through signing up, creating a database, and importing your data.

link:https://aura.support.neo4j.com/hc/en-us/articles/360037562253-Working-with-Neo4j-Aura[Get started with Neo4j Aura^, role="button feature-box_button"]

// * link:/developer/create-database[Create database]
// * link:/developer/change-password[Change password]

[#connecting-aura]
== Connect to your Aura database

These tutorials explain how to connect to your Aura database from other Neo4j tools.

* link:/developer/aura-connect-neo4j-desktop[Connect from Neo4j Desktop]

* link:/developer/aura-connect-cypher-shell[Connect from Cypher Shell]

* link:/developer/aura-connect-driver[Connect from your application]

[#importing-data]
== Importing data

Aura considers the protection of users' data to be of paramount importance.
There are therefore some constraints to keep in mind when using your favourite import tools to load data into an Aura database.
The guide below covers these in detail.

link:/developer/aura-data-import[Importing data into Neo4j Aura, role="button feature-box_button"]

// These tutorials show how to import data into an Aura database.

// * link:/developer/import-existing-database[Import an existing database]

// * Import from Web APIs

[#deploying-applications]
== Deploying applications to Aura

These tutorials explain how to build full stack applications with Aura.

* link:/developer/aura-grandstack[Deploying a GRANDstack application]

[#managing-aura]
== Manage your Aura database

You've created your Aura database, imported your data, and are now running your application against it.
Now you want to know what's happening inside the database.
The tutorial below explains the available options for monitoring your database.

link:/developer/aura-monitor[Monitor your database, role="button feature-box_button"]

[#dbaas-resources]
== Questions?
Additional guides and help are available on the link:https://aura.support.neo4j.com/hc/en-us[Aura support^] page.

You can also ask questions and connect with other people launching Neo4j Aura at the
https://community.neo4j.com/c/neo4j-graph-platform/cloud[cloud topic on the Community Site^].
