= Guide to importing data into Neo4j

This guide will help get your data into Neo4j wherever it happens to come from and regardless of how much of it there is.

Existing data can come in many shapes and sizes but for this guide we're going to use a relational database as that's one of the most common data sources from which people export data into Neo4j.

We'll use the Postgres relational database and the link:https://code.google.com/p/northwindextended/downloads/detail?name=northwind.postgre.sql&can=2&q=[NorthWind data set] as our example.

Regardless of the source we typically won't have our data already structured as a graph so we'll first need to design a graph model - you can learn how to do that in our link:../../build-a-graph-data-model/guide-intro-to-graph-modeling/index.html[modeling guide].

For this data set the following graph model serves as a first iteration:

<insert image of model here>

Now that we know what we'd like our graph to look like we need to extract the data from Postgres so we can create it. The easiest way to do that is to export the appropriate tables in CSV format.

Postgres' 'copy' command lets us execute a SQL query and write the result to a CSV file:

[source, sql]
----
Copy (SELECT * FROM orders
      left outer join customers ON customers."CustomerID" = orders."CustomerID"
      left outer join employees ON employees."EmployeeID" = orders."EmployeeID"
      left outer join order_details ON order_details."OrderID" = orders."OrderID"
      left outer join products ON products."ProductID" = order_details."ProductID"
      left outer join suppliers ON suppliers."SupplierID" = products."SupplierID"
      left outer join categories ON categories."CategoryID" = products."CategoryID")
      To '/tmp/customerDb.csv' With CSV header;
----

Next we'll create some indexes on the (label, property) pairs that we're going to create in Neo4j.

[source, cypher]
----
create index on :Product(productId)
----

[source, cypher]
----
create index on :Category(categoryId)
----

[source, cypher]
----
create index on :Order(OrderId)
----

[source, cypher]
----
create index on :Employee(employeeId)
----

[source, cypher]
----
create index on :Supplier(supplierId)
----

After we've done that we'll use Cypher's link:http://docs.neo4j.org/chunked/stable/query-load-csv.html[LOAD CSV] command to transform the contents of the CSV file into a graph structure.

[source, cypher]
----
LOAD CSV WITH HEADERS FROM "file:/tmp/customerDb.csv" AS row

MERGE (order:Order {orderId: row.OrderID})

MERGE (product:Product {productId: row.ProductID})
ON CREATE SET product.name = row.ProductName

MERGE (supplier:Supplier {supplierId: row.SupplierID})
ON CREATE SET supplier.companyName = row.SupplierCompanyName

MERGE (employee:Employee {employeeId: row.EmployeeID})

MERGE (category:Category {categoryId: row.CategoryID})
ON CREATE SET category.name = row.CategoryName

MERGE (employee)-[:SOLD]->(order)
MERGE (order)-[:PRODUCT]->(product)
MERGE (supplier)-[:SUPPLIES]->(product)
MERGE (product)-[:PART_OF]->(category)
----



We can now query the graph...
