= Neo4j Ecosystem
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 1
:section: Neo4j Ecosystem
:section-link: ecosystem

.Goals
[abstract]
Neo4j is supported by a rich ecosystem of libraries, tools, drivers and guides provided by partners, users and community contributors. 
We want to give an overview about what's available and link to the original sources.
We try to focus on the freely available solutions here, and provide links to commercial options were appropriate.

.Prerequisites
[abstract]
You should have a basic understanding of the link:/developer/graph-database#property-graph[property graph model] and have completed the link:/developer/guide-data-modeling[modeling guide].
If you link:/download[download] and install the Neo4j server you'll be able to follow along with the examples.

[role=expertise]
{level}

toc::[]

=== Neo4j Ecosystem

Neo4j is a graph database management system, it comes with an implementation of the database, a server and a web interface.
There are APIs, documentation and examples for operations, certain use-cases and applications.

To make it easy to make Neo4j part of a system infrastructure there are many more aspects to be addressed.
Those additional aspects cover many different areas: drivers, visualization, ETL and BI tools, integration platforms, development tools and additional frameworks and libraries on top of Neo4j that allow you to address certain problems faster and with less effort.

Being and open source database we benefit from users and contributors in our ecosystem that 

=== How to Contribute

=== Drivers

=== Graph Compute

=== Hosting

=== Visualization libraries

==== Alchemy.js

==== Gephi

=== Business Intelligence

==== QlikView/QlikSense Integration

=== Software Analytics

==== jQAssistant

=== Application Frameworks

=== Libraries

* graphaware

=== Database Introspection & Migration

http://fbiville.github.io/liquigraph

sylvadb

////
NeoProfiler M. David Allen
https://github.com/moxious/neoprofiler
////
