= Graph Algorithms
:slug: graph-algorithms
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 2
:section: Neo4j Integrations
:section-link: integration

toc::[]

== Introduction

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.

They can provide insights on relevant entities (centralities, ranking) in the graph or inherent structures such as communities (community-detection, graph-partitioning, clustering).

== Graph Algorithms Library

Neo4j Graph Algorithms is a library that provides efficiently implemented, parallel versions of common graph algorithms for Neo4j 3.x exposed as link:/developer/cypher/[Cypher^] procedures.

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/55uB_t0RKTE" frameborder="0" allowfullscreen></iframe>
++++

It currently contains implementations for the following algorithms:

include::https://github.com/mneedham/neo4j-graph-algorithms/raw/docs-tweaks/readme.adoc[tag=algorithms]

== Installation

* Download the library from the https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases[downloads page^] and put the jar into `$NEO4J_HOME/plugins`
* Add `dbms.security.procedures.unrestricted=algo.*` to `$NEO4J_HOME/conf/neo4j.conf`
* Restart Neo4j

We're now ready to start using the graph algorithms.
Run the following query to check that the algorithms library has been picked up by Neo4j:

[source,cypher]
```
CALL dbms.procedures() YIELD name, signature, description
WHERE name starts with "algo"
RETURN name, signature, description
```

If we don't see any rows we'll need to revisit the installation instructions.

== Further reading

We have an https://neo4j-contrib.github.io/neo4j-graph-algorithms/#_algorithms_2[Algorithms section^] in the user guide which goes into the history of each algorithm and the use cases for which they're applicable.

Our colleague Amy Holder has also written an excellent blog post - https://neo4j.com/blog/top-13-resources-graph-theory-algorithms/[The Top 13 Resources for Understanding Graph Theory & Algorithms^] - in which she lists some of her favorite books and online courses.
