= Refactoring
:slug: graph-model-refactoring
:level: Intermediate
:section: Cypher Query Language
:section-link: cypher
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1

.Goals
[abstract]
Building on the Cypher Basics guides, this guide covers the temporal date types introduced in Neo4j 3.4.
Upon finishing this guide, you should be able to create, compare, and format these values.

.Prerequisites
[abstract]
You should be familiar with link:/developer/get-started/graph-database[graph database] concepts and the link:/developer/get-started/graph-database#property-graph[property graph model].
This guide is a continuation of the concepts discussed in the previous Cypher sections.
You should be familiar with link:/developer/cypher/cypher-query-language[MATCH], link:/developer/cypher/cypher-basics-ii/[Create/Update/Delete], and link:/developer/cypher/filtering-query-results/[Filtering] concepts before walking through this guide.

[role=expertise]
{level}

[#initial-dataset]
== Initial dataset

We'll start with the movies dataset, which 


[#cypher-resources]
=== Resources

This guide has shown how to work more effectively with temporal types using the APOC libary.
Below are some resources for learning more about using Temporal types in Neo4j:

* link:https://neo4j.com/docs/cypher-manual/current/syntax/temporal[Temporal Datatypes^]
* link:https://neo4j.com/developer/kb/neo4j-string-to-date/[Knowledge Base: Converting strings to dates^]
* link:https://neo4j.com/developer/neo4j-apoc/[APOC Library^]
** link:https://neo4j.com/docs/labs/apoc/current/temporal/datetime-conversions/[Date parsing^]
** link:https://neo4j.com/docs/labs/apoc/3.4/temporal/temporal-conversions/[Temporal Functions^]
