== Neo4j Movies Example Application

=== Stack

* Java-Web Application
* http://www.sparkjava.com/[Spark-Java] (Micro-Webframework)
* https://github.com/neo4j-contrib/neo4j-jdbc#minimum-viable-snippet[Neo4j-JDBC] with Cypher
* Neo4j-Server
* Frontend: jquery, bootstrap, http://d3js.org/[d3.js]

=== Endpoints:

Get Movie

----
// JSON object for single movie with cast
curl http://neo4j-movies.herokuapp.com/movie/The%20Matrix

// list of JSON objects for movie search results
curl http://neo4j-movies.herokuapp.com/search?q=matrix

// JSON object for whole graph viz (nodes, links - arrays)
curl http://neo4j-movies.herokuapp.com/graph
----

=== Setup

Spark is a micro-webframework to easily define routes for endpoints and provide their implementation.
In our case the implementation calls the `MovieService` which has one method per endpoint that returns Java collections
which are turned into JSON using Gson.

The `MovieService` uses the Neo4j-JDBC driver to execute queries against the transactional endpoint of Neo4j-Server.
You add the dependency to the JDBC driver in your `pom.xml`:

[source,xml]
----
include::pom.xml[tags=jdbc-dependency]
----

To use the JDBC driver you provide a connection URL, e.g. `jdbc:neo4j:localhost:7474`, get a `Connection`
which then can be used to create `PreparedStatement`s with your Cypher query.

You would then set parameters on your statement, please note that only numeric parameter-names are possible, _starting from 1_.

To access the `ResultSet` you call the cursor method `rs.next()` in a while loop, within which you can access the result-data by `rs.getString("columnName")` where the column name is the `RETURN` clause alias for each column.

[source,java]
----
Connection con = DriverManager.getConnection("jdbc:neo4j://localhost:7474/");

String query = "MATCH (:User {name:{1}})-[:FRIEND]->(f:User) RETURN f.name as friend";

try (PreparedStatement stmt = con.prepareStatement(query)) {

    stmt.setString(1,"John");

    try (ResultSet rs = stmt.executeQuery()) {
        while(rs.next()) {
             System.out.println(rs.getString("friend"));
        }
    }
}
----

=== Run locally:

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser].
Then install the Movies data-set with `:play movies`, click the statement, and hit the triangular "Run" button.

Start this application with:

[source,shell]
----
mvn compile exec:java
----

Go to http://localhost:8080

You can search for movies by title or and click on any entry .

=== Deploy to Heroku

We want to install our application to the cloud, for instance the http://heroku.com[Heroku] PaaS.
We will also use the http://graphenedb.com[GraphenDB] Neo4j Database Hosting Add-On.

Install the https://toolbelt.heroku.com/[Heroku Toolbelt] and git.

Then run these commands

[source,shell]
----
# initialize git repository and add files
git init
git add .
git commit -m"my neo4j movies app"

# create heroku application, please change the app-name
export app=my-neo4j-movies-app
heroku apps:create $app

# add free graphenedb hosting
heroku addons:add graphenedb:chalk --app $app

# configure your app to use the add-on
heroku config:set NEO4J_REST_URL=GRAPHENEDB_URL --app $app

# deploy to heroku
git push heroku master

# open application
heroku open --app $app

# open addon admin page
heroku addons:open graphenedb
----

In the Graphenedb-UI use "Launch Neo4j Admin UI".
In the Neo4j-Browser run the `:play movies` as of the install instructions above.

Then your app is ready to roll.



