== Neo4j Movies Example Application

=== Stack

* Java-Web Application
* http://www.sparkjava.com/[Spark-Java] (Micro-Webframework)
* Neo4j-JDBC w/ Cypher
* Neo4j-Server
* Frontend: jquery, bootstrap, http://d3js.org/[d3.js]

=== Endpoints:

Get Movie

----
// JSON object for single movie with cast
curl http://neo4j-movies.herokuapp.com/movie/The%20Matrix

// list of JSON objects for movie search results
curl http://neo4j-movies.herokuapp.com/search?q=matrix

// JSON object for whole graph viz (nodes, links - arrays)
curl http://neo4j-movies.herokuapp.com/graph
----

=== Run locally:

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser].
Then install the Movies data-set with `:play movies`, click the statement, and hit the triangular "Run" button.

Start this application with:

[source,shell]
----
mvn compile exec:java
----

Go to http://localhost:8080

You can search for movies by title or and click on any entry .

=== Deploy to Heroku

We want to install our application to the cloud, for instance the http://heroku.com[Heroku] PaaS.
We will also use the http://graphenedb.com[GraphenDB] Neo4j Database Hosting Add-On.

Install the https://toolbelt.heroku.com/[Heroku Toolbelt] and git.

Then run these commands

[source,shell]
----
# initialize git repository and add files
git init
git add .
git commit -m"my neo4j movies app"

# create heroku application, please change the app-name
export app=my-neo4j-movies-app
heroku apps:create $app

# add free graphenedb hosting
heroku addons:add graphenedb:chalk --app $app

# configure your app to use the add-on
heroku config:set NEO4J_REST_URL=GRAPHENEDB_URL --app $app

# deploy to heroku
git push heroku master

# open application
heroku open --app $app

# open addon admin page
heroku addons:open graphenedb
----

In the Graphenedb-UI use "Launch Neo4j Admin UI".
In the Neo4j-Browser run the `:play movies` as of the install instructions above.

Then your app is ready to roll.



