= Neo4j Administration
:slug: in-production
:section: Neo4j Administration
:section-link: in-production
:section-level: 1
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1
:author: Jennifer Reif
:neo4j-version: 4.0
:category: operations
:tags: administration, production, architecture, performance, deployment

[#deploy-neo4j]
Are you preparing to deploy Neo4j into production and handle management and operation of the system?
This section features guides and tutorials to help you understand how to deploy, maintain, and optimize Neo4j.

When running Neo4j in production, we want to maximize the processes and configuration for scalability, monitoring, and day-to-day operations.
We will cover how to run Neo4j in various environments, tune performance, operate databases, configure security, set up an architecture, and more.

[#maximize-features]
== Taking advantage of the latest features

Each new version of Neo4j offers new features and capabilities, as well as adjustments and improvements to existing functionality.
Operating in the changing environment requires some knowledge and training of the features themselves, as well as how they apply to your particular environment.

Various guides throughout this section will cover topics on key operational features and how they work.

link:/developer/manage-databases/[Manage Multiple Databases] +
link:/developer/multi-tenancy/[Multi-Tenancy: A Worked Example] +
link:/developer/neo4j-fabric-sharding/[Sharding Graph Data]

[#performance-tuning]
== Performance Tuning

Running business critical or even demanding applications in production requires a robust system.
It probably also includes some optimizations to configurations, architecture, or queries in order to maximize speed and reliability benefits for the entire system.

From learning tips and best practices calculating the recommended hardware configuration for your Neo4j deployment to troubleshooting performance issues and improving performance, there are guides in this section to tackle many of these common problems.

link:/developer/guide-performance-tuning/[Neo4j Performance Tuning]

[#architecture-deployment]
== Architecture & Deployment

Deployment options for databases are often flexible to handle varying environments and operating requirements, and Neo4j is no exception.
The deployment chosen will depend on existing system architecture, scalability needs, access locations and regions, and integration needs with other systems.

Some of these guides cover information on handling different types of deployments, including how to deal with Neo4j in database clusters and how to containerize Neo4j with Docker.

link:/developer/docker/[Running Neo4j in Docker] +
link:/developer/docker-run-neo4j/[How-To: Run Neo4j in Docker] +
link:/developer/guide-clustering-neo4j/[Set up a Neo4j Cluster]

Public and/or private cloud provider deployment options are also possible.
Cloud-hosted offerings and how to deploy Neo4j to infrastructure or platform providers is documented and referenced in the link:/developer/guide-cloud-deployment/[cloud] and link:/developer/aura-cloud-dbaas/[Neo4j Aura] sections.
