= Neo4j Online Meetup
:slug: online-meetup
:toc:
:toc-placement!:
:toc-title: Topics
:toclevels: 1
:section: Contributing to Neo4j
:section-link: resources
:section-level: 1

== Join us for online sessions streamed on YouTube Live

In February 2017 we started running online sessions so that people in regions that don't have physical meetups can get fresh Neo4j content.

We post new events on the link:https://www.meetup.com/Neo4j-Online-Meetup/[Neo4j Online Meetup] group so be sure to link:https://www.meetup.com/Neo4j-Online-Meetup/join[join the group] to be notified about these.

You can also link:https://www.youtube.com/neo4j?sub_confirmation=1[subscribe to our YouTube channel].

++++
<script src="https://apis.google.com/js/platform.js"></script>

<div class="g-ytsubscribe" data-channelid="UCvze3hU6OZBkB1vkhH2lH9Q" data-layout="full" data-count="default"></div>
++++

== Live session

Our link:https://www.meetup.com/Neo4j-Online-Meetup/events/237696549/[next live streamed event] is on 2nd March 2017 at 17:00 UTC.

link:https://twitter.com/barrasadv[Jesus Barrasa], Senior Pre Sales Engineer at Neo4j, and link:https://twitter.com/markhneedham[Mark Needham], Software Engineer (Clustering) at Neo4j, will explore how the two graph worlds of semantic technologies and graph databases relate.

Don't forget to link:https://www.meetup.com/Neo4j-Online-Meetup/events/237696549/[register on the meetup page].

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/SvwIqzaoYMo" frameborder="0" allowfullscreen></iframe>
++++

== Past sessions

Below you can watch videos of previous presentations.

=== Exploring TrumpWorld with Neo4j
14th February 2017 at 17:00 UTC

In this talk link:https://twitter.com/mesirii[Michael Hunger], Head of Developer Relations EMEA at Neo4j, showed us how to explore Buzzfeed's TrumpWorld dataset.

++++
<iframe width="560" height="315" src="https://www.youtube.com/embed/pW9boJoUxO0" frameborder="0" allowfullscreen></iframe>
++++
