= Neo4j from c
:slug: c
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 2
:section: Develop with Neo4j
:section-link: language-guides

.Goals
[abstract]
If you are a C or pass:[C++] developer, this guide provides an overview of options for connecting from C and pass:[C++] to Neo4j.

.Prerequisites
[abstract]
You should be familiar with link:/developer/get-started/graph-database[graph database concepts] and the property graph model.
You should have link:/download[installed Neo4j] and made yourself familiar with our link:/developer/cypher[Cypher Query language].

[role=expertise]
{level}

toc::[]

// tag::intro[]
=== Neo4j for C Developers

Despite several attempts, Neo4j's HTTP was not well supported in the C community.
This changed with the advent of the binary protocol in Neo4j 3.0.
Chris Leishman wrote a very comprehensive and full featured c-client library for the binary protocol.

// image::[float=right]

// end::intro[]

include::../_includes/community-driver-notice.adoc[]

=== libneo4j-client

Libneo4j-client is a full featured c-library for interacting with Neo4j's binary protocol.
It supports all wire commands, as well as the security features like auth and TLS.

A very performant shell client is provided together with the library.

[NOTE]
This library is not only meant to be used from C/pass:[C++] programs directly, but also as convenient, low-level integration library for other languages like PHP, Ruby and Python.

[cols="1,4"]
|===
| icon:user[] Author | http://twitter.com/cleishm[Chris Leishman]
// | icon:play-circle[] Example Project | {examples}/movies-clojure-neocons
| icon:gift[] Package | https://clojars.org/clojurewerkz/neocons
| icon:github[] Source | https://github.com/cleishm/libneo4j-client
| icon:book[] Docs | https://cleishm.github.com/libneo4j-client
|===
