= Neo4j Integration
:slug: integration
:section: Neo4j integration
:section-link: integration
:section-level: 1
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1

[#neo4j-integration]
Neo4j is supported by a rich ecosystem of libraries, tools, drivers, and guides provided by partners, users, and community contributors.
We want to give an overview about what's available and link to the original sources.
We try to focus on the freely available solutions here, and provide links to commercial options were appropriate.

Check out our link:../integration/ecosystem[ecosystem contributions] to further boost your Neo4j productivity.

[#integration-projects]
== Neo4j Integration Projects
* link:../integration/apache-spark[Neo4j and Apache Spark]
* link:../integration/elastic-search[Neo4j and Elastic{Search}]
* link:../integration/mongodb[Neo4j and MongoDB]
* link:../integration/cassandra[Neo4j and Cassandra]
// * link:../integration/apache-hadoop[Neo4j and Hadoop]
* link:../integration/docker[Neo4j and Docker]
