= Docker image for Neo4j 3.x
:slug: docker-30
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Contents
:toclevels: 1
:section: Neo4j Integrations
:section-link: integration

[NOTE]
Docker does not run natively on Mac OSX or Windows.
For running Docker on https://docs.docker.com/engine/installation/mac/[Mac OSX] and https://docs.docker.com/engine/installation/windows/[Windows] please consult the Docker documentation.

== Overview

// tag::get-started[]

The image exposes three ports (`7474`, `7473` and `7687`) for HTTP, HTTPS and Bolt access to the Neo4j API and a volume (`/data`) to allow the database to be persisted outside its container.

----
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    neo4j:3.0
----

Point your browser at `http://localhost:7474` on Linux or `http://$(docker-machine ip default):7474` on OSX.

[NOTE]
All the volumes in this documentation are stored under `$HOME` in order to work on OSX where `$HOME` is automatically mounted into the machine VM.
On Linux the volumes can be stored anywhere.

[NOTE]
By default Neo4j requires authentication.
You have to login with `neo4j/neo4j` at the first connection and set a new password.

// end::get-started[]

toc::[]

== Neo4j editions

The Neo4j comes in two editions: Community and Enterprise.

Neo4j Enterprise Edition is designed for commercial deployments where scale and availability are important.
Use of Neo4j Enterprise Edition requires a commercial license agreement with Neo Technology.
Please see http://neo4j.com/licensing/[Neo4j licensing] for details.

Tags are available for both editions.
Version-specific Enterprise tags have an `-enterprise` suffix (like `neo4j:3.0.0-enterprise`), Community tags have no suffix (like `neo4j:3.0.0`).
The latest Enterprise release is available as `neo4j:enterprise`.

== Upgrading

There are several changes in Neo4j 3.0 that affect the Docker image.

* Neo4j now exposes two ports: 7474 and 7687.
* The configuration has been overhauled; the environment variables that are available have been changed to reflect the new settings (see below for details).

If you are supplying your own configuration files rather than using environment variables then you will need to migrate those.
See the http://neo4j.com/docs/operations-manual/3.0/#deployment-upgrading[manual] for details.

== Docker configuration

=== File descriptor limit

Neo4j may use a large number of file descriptors if many indexes are in use or there is a large number of simultaneous database connections.

Docker controls the number of open file descriptors in a container; the limit depends on the configuration of your system.
We recommend a limit of at least 40000 for running Neo4j.

To check the limit on your system, run this command:

----
docker run neo4j:3.0 \
    bash -c 'echo Soft limit: $(ulimit -Sn); echo Hard limit: $(ulimit -Hn)'
----

To override the default configuration for a single container, use the `--ulimit` option like this:

----
docker run \
    --detach \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --ulimit=nofile=40000:40000
    neo4j:3.0
----

== Neo4j configuration

The default configuration provided by this image is intended for learning about Neo4j, but must be modified to make it suitable for production use.
In particular the memory assigned to Neo4j is very limited (see `NEO4J_CACHE_MEMORY` and `NEO4J_HEAP_MEMORY` below), to allow multiple containers to be run on the same server.
You can read more about configuring Neo4j in the http://neo4j.com/docs/operations-manual/3.0/#configuration-settings[manual].

There are three ways to modify the configuration depending on how much you need to customize the image.

=== Environment variables

Pass environment variables to the container when you run it.

----
docker run \
    --detach \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --env=NEO4J_dbms_memory_pagecache_size=4G \
    neo4j:3.0
----

The following environment variables are available:

* `NEO4J_AUTH`: controls authentication, set to `none` to disable authentication or `neo4j/<password>` to override the default password (see the http://www.neo4j.com/docs/operations-manual/3.0/#security[manual] for details)
* `NEO4J_dbms_memory_pagecache_size`: the size of Neo4j's native-memory cache, defaults to 512M
* `NEO4J_dbms_memory_heap_maxSize`: the size of Neo4j's heap in MB, defaults to 512
* `NEO4J_dbms_txLog_rotation_retentionPolicy`: the retention policy for logical logs, defaults to `100M size`
* `NEO4J_dbms_allowFormatMigration`: set to `true` to enable upgrades, defaults to `false` (see the http://www.neo4j.com/docs/operations-manual/3.0/#upgrading[manual] for details)

==== Enterprise Edition

The following settings control features that are only available in the Enterprise Edition of Neo4j.

* `NEO4J_dbms_mode`: the database mode, defaults to `SINGLE`, set to `HA` to create a cluster
* `NEO4J_ha_serverId`: the id of the server, must be unique within a cluster
* `NEO4J_ha_host_coordination`: the address (including port) used for cluster coordination in HA mode, this must be resolvable by all cluster members
* `NEO4J_ha_host_data`: the address (including port) used for data transfer in HA mode, this must be resolvable by all cluster members
* `NEO4J_ha_initialHosts`: comma-separated list of other members of the cluster

See below for an example of how to configure HA clusters.

=== `/conf` volume

To make arbitrary modifications to the Neo4j configuration, provide the container with a `/conf` volume.

----
docker run \
    --detach \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/conf:/conf \
    neo4j:3.0
----

Any configuration files in the `/conf` volume will override files provided by the image.
This includes values that may have been set in response to environment variables passed to the container by Docker.
So if you want to change one value in a file you must ensure that the rest of the file is complete and correct.

To dump an initial set of configuration files, run the image with the `dump-config` command.

----
docker run --rm\
    --volume=$HOME/neo4j/conf:/conf \
    neo4j:3.0 dump-config
----

=== Build a new image

For more complex customization of the image you can create a new image based on this one.

----
FROM neo4j:3.0
----

If you need to make your own configuration changes, we provide a hook so you can do that in a script:

----
COPY extra_conf.sh /extra_conf.sh
----

Then you can pass in the `EXTENSION_SCRIPT` environment variable at runtime to source the script:

----
docker run -e "EXTENSION_SCRIPT=/extra_conf.sh" cafe12345678
----

When the extension script is sourced, the current working directory will be the root of the Neo4j installation.

== Neo4j HA

(This feature is only available in Neo4j Enterprise Edition.)

In order to run Neo4j in HA mode under Docker you need to wire up the containers in the cluster so that they can talk to each other.
Each container must have a network route to each of the others and the `NEO4J_ha_host_coordination`, `NEO4J_ha_host_data` and `NEO4J_ha_initialHosts` environment variables must be set accordingly (see above).

Within a single Docker host, this can be achieved as follows.

----
docker network create --driver=bridge cluster

docker run --name=instance1 --detach --publish=7474:7474 --publish=7687:7687 --net=cluster --hostname=instance1 \
    --env=NEO4J_dbms_mode=HA --env=NEO4J_ha_serverId=1 \
    --env=NEO4J_ha_host_coordination=instance1:5001 --env=NEO4J_ha_host_data=instance1:6001 \
    --env=NEO4J_ha_initialHosts=instance1:5001,instance2:5001,instance3:5001 \
    neo4j:enterprise-3.0

docker run --name=instance2 --detach --publish 7475:7474 --publish=7688:7687 --net=cluster --hostname=instance2 \
    --env=NEO4J_dbms_mode=HA --env=NEO4J_ha_serverId=2 \
    --env=NEO4J_ha_host_coordination=instance2:5001 --env=NEO4J_ha_host_data=instance2:6001 \
    --env=NEO4J_ha_initialHosts=instance1:5001,instance2:5001,instance3:5001 \
    neo4j:enterprise-3.0

docker run --name=instance3 --detach --publish 7476:7474 --publish=7689:7687 --net=cluster --hostname=instance3 \
    --env=NEO4J_dbms_mode=HA --env=NEO4J_ha_serverId=3 \
    --env=NEO4J_ha_host_coordination=instance3:5001 --env=NEO4J_ha_host_data=instance3:6001 \
    --env=NEO4J_ha_initialHosts=instance1:5001,instance2:5001,instance3:5001 \
    neo4j:enterprise-3.0
----

See the http://neo4j.com/docs/operations-manual/3.0/#ha-setup-tutorial[manual] for more details of Neo4j HA.

== User-defined procedures

To install user-defined procedures, provide a `/plugins` volume containing the jars.

----
docker run --publish 7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/plugins:/plugins neo4j:3.0
----

See the http://neo4j.com/docs/developer-manual/3.0/#procedures[manual] for more details on procedures.

== Neo4j shell

The Neo4j shell can be run locally within a container using a command like this:

----
docker exec --interactive <container> bin/neo4j-shell
----

== TLS support

To use your own key and certificate, provide an `/ssl` volume with the key and certificate inside.
The files must be called `neo4j.key` and `neo4j.cert`.
You must also publish port `7473` to access the HTTPS endpoint.

----
docker run --publish 7473:7473 --publish=7687:7687 --volume $HOME/neo4j/ssl:/ssl neo4j:3.0
----
