== Spring Boot Neo4j JDBC - Movies Example Application

Even if http://neo4j.org[Neo4j] is all about graphs, its graph query language http://neo4j.org/learn/cypher[Cypher] is well suited to be used with JDBC (Java Database Connectivity).
As you probably know, JDBC is a common way to connect to a datastore, especially since there
are a lot of tooling and connectors written around it in the Business Intelligence, Data Migration, and ETL world.

The Neo4j JDBC driver works with Neo4j Server in version 1.9.x and 2.x and with embedded and in-memory databases.
It allows you to (transactionally) execute parametrized Cypher statements against your Neo4j database to either create,
query or update data.

Here we integrate Neo4j-JDBC with Spring-Boot and the traditional Spring-JDBC (JDBCTemplate) and Spring Web-MVC to create the backend.


=== The Stack

These are the components of our mini Web Application:

* Application Type:         Java-Web Application
* Web framework:            Spring-Boot with Spring-WebMVC
* Persistence Access:       Spring-JDBC
* Neo4j Database Connector: https://github.com/neo4j-contrib/neo4j-jdbc#minimum-viable-snippet[Neo4j-JDBC] with Cypher
* Database:                 Neo4j-Server
* Frontend:                 jquery, bootstrap, http://d3js.org/[d3.js]

=== Endpoints:

Get Movie

----
// JSON object for single movie with cast
curl http://neo4j-movies.herokuapp.com/movie/The%20Matrix

// list of JSON objects for movie search results
curl http://neo4j-movies.herokuapp.com/search?q=matrix

// JSON object for whole graph viz (nodes, links - arrays)
curl http://neo4j-movies.herokuapp.com/graph
----

=== Setup

Spring Boot is a rapid application development environment, bundling necessary Spring modules into easy-to-use `starter` packages.

It is based on annotation-based Java config and pre-configuring the packages with sensible defaults.
You can adapt them in a single `application.properties` config file.

You add the dependency to the JDBC driver and Spring-Boot-Starters to your `pom.xml`:

[source,xml]
----
include::pom.xml[tags=dependencies]
----

For the backend we use a Spring-WebMVC `@RestController` whose service methods access an autowired `JdbcTemplate`.

Currently we get the `NEO4J_URL` from a system property, but it should be equally simple to get it from an entry in `application.properties`.

Using the JDBC-template with Cypher is easy. 
Here is an example from the `/movie` endpoint:

[source,java]
----
include::src/main/java/movies/spring/jdbc/SampleMovieApplication.java[tags=jdbctemplate]
----

You would then set parameters on your statement.
Please note that only numeric parameter names are possible, _starting from 1_.

You can use all known `JdbcTemplate` methods, like `queryForObjects`, `queryForMap` and `RowMapper` or `ResultSetCallBack` as you're used to.

=== Run locally:

Start your local Neo4j Server (http://neo4j.com/download[Download & Install]), open the http://localhost:7474[Neo4j Browser].
Then install the Movies data-set with `:play movies`, click the statement, and hit the triangular "Run" button.

Start this application with:

[source,shell]
----
mvn spring-boot:run
----

Go to http://localhost:8080

You can search for movies by title and/or click on any entry.

////
=== Deploy to CloudFoundry

include::../../Readme.adoc[tags=heroku]
////
