= Browser Guide Reference List
:slug: browser-guide-list
:level: Beginner
:section: Documentation and Resources
:section-link: resources
:sectanchors:
:toc:
:toc-title: Contents
:toclevels: 1
:icons: font

Neo4j Browser provides many interactive guides for learning concepts and tools with Neo4j.
From data import to graph algorithms to working with RDF data, there is likely an interactive browser guide out there to walk through it.

If there isn't one that fits your needs, you can create one and publish it to the community or internally at your company.
For more information on how to do that, check out our guide for link:/developer/guide-create-neo4j-browser-guide[creating a custom Browser guide].

[#built-in]
== Neo4j Browser built-in guides

Some guides ship with Neo4j Browser out-of-the-box, no matter what system or installation we are working on.
Below is a list of guides with descriptions for what is provided.

[cols="2*^",frame=all]
|===
|Guide Command           |Description

|`:play intro`           |Navigating Neo4j Browser
|`:play concepts`        |Property graph model concepts
|`:play cypher`          |Cypher basics - create, match, patterns
|`:play movie-graph`     |Queries and recommendations with Cypher - movie use case
|`:play northwind-graph` |Translate and import relational data to graph
|`:play start`           |Main guide (loads when Browser opens) - concepts, write-code, system info
|`:play write-code`      |Shows both guides for movie graph and northwind graph
|===

[#public-guides]
== Public Guides

Other guides are created by Neo4j staff and community members to help others learn Neo4j or how to use the tools in its ecosystem.
We have some amazing work in this area, and we always welcome contributions!

List coming soon!

////
Below is a list of guides with descriptions for what is available.

[cols="2*^",frame=all]
|===
|Guide Command           |Description

|===

////

== Resources

* Tutorial: link:/developer/guide-create-neo4j-browser-guide/[Create your own Browser guide]