= Neo4j Performance Tuning
:slug: guide-performance-tuning
:level: Intermediate
:toc:
:toc-placement!:
:toc-title: Overview
:toclevels: 1
:section: Neo4j in Production
:section-link: in-production

.Goals
[abstract]
This guide gives an overview on memory configuration, logical log configuration and Linux open files configuration.

.Prerequisites
[abstract]
You should know how to link:/download[download] and install Neo4j on your system.
If you are a developer you should be accustomed to the graph data model and have written your Neo4j application.

[role=expertise]
{level}

toc::[]

== Memory Configuration guidelines

An in-depth description on this topic is available here: {manual}/configuration-io-examples.html

There are three types of memory to consider:

* OS Memory
* Page Cache
* JVM Heap

=== OS Memory Sizing

Some memory must be reserved for all activities on the server that are *not* Neo4j related.
1G is a good starting default

=== Page Cache Sizing

Page cache, or _mapped memory_, is used to cache the Neo4j data as stored on disk.
The goal is to size the page cache so that all the graph data fits into it.
Ensuring that all the graph content is cached into memory will help avoid costly disk access.


The size of the page cache is defined by the paramter `dbms.pagecache.memory` in the file `NEO4J_HOME/conf/neo4j-server.properties`.


=== JVM Heap Sizing

The size of the JVM heap is an important aspect of the performance of any Java application. 
For a more thorough discussion on this topic, refer to {manual}/performance-guide.html#_configuring_heap_size_and_gc

* Tuning of the standalone server: Edit the file `NEO4J_HOME/conf/neo4j-wrapper.conf`.

* Tuning Neo4j embedded: Specify paramters by adding command line flags to the java process.

Generally speaking, it is beneficial to configure a large heap space, at the same time as it is important to ensure that the heap fits into the RAM of the computer.
The JVM heap size is determined by the parameters `wrapper.java.initmemory` and `wrapper.java.maxmemory`.
It is recommended to set these two parameters to the same number.

The JVM heap is divided into an _old generation_ and a _new generation_
The proportions between these will affect the garbage collector's behavior.
Tuning of the generation properties is done by specifying the parameter _wrapper.java.additional=-XX:NewRatio=N_, where N is typically between 2 and 8.
It is recommended to configure the JVM to use the G1 garbage collector by setting the parameter _wrapper.java.additional=-XX:+UseG1GC

Example: Specify JVM Parameters in `NEO4J_HOME/conf/neo4j-wrapper.conf`

----
wrapper.java.initmemory=24512
wrapper.java.maxmemory=24512
wrapper.java.additional=-XX:+UseG1GC
wrapper.java.=-XX:NewRatio=2
----

[role=side-nav]
* {manual}/operations.html[Operations,role=manual]
* {manual}/configuration.html[Configuration & Performance,role=manual]
* http://maxdemarzi.com/2013/11/25/scaling-up/[Scaling Up Neo4j,role=blog]
* link:/support[Neo4j Professional Support]


== Logical Logs

Logical logs in Neo4j are the source of truth in scenarios where the database needs to be recovered after a crash or similar.
Logs are rotated every now and then (defaults to when they surpass 25 Mb in size) and the number of legacy logs to keep can be configured.

It is recommended that the `keep_logical_logs` parameter be set to `7 days`

== Number of Open Files on Linux

The usual default of `1024` is often not enough, especially when many indexes are used or a server installation sees too many connections (network sockets also count against that limit).
Users are therefore encouraged to increase that limit to a healthy value of `40000` or more, depending on usage patterns.
Setting this value via the ulimit command is possible only for the root user and for that session only.  To set the value system wide you have to follow the instructions for your platform ({manual}/linux-performance-guide.html#_setting_the_number_of_open_files[Linux]).
